server {
    listen 3025;
    server_name localhost;
    client_max_body_size 100M; # Limite de upload de arquivos

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Redireciona rotas inexistentes fisicamente para o React index.html
        try_files $uri $uri/ /index.html;
    }

    # Encaminha chamadas /api para o container do backend
    location /api/ {
        proxy_pass http://backend:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        # Otimizações de timeout para chamadas longas / SSE
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        proxy_connect_timeout 60s;
    }

    # Encaminha solicitações de uploads para os arquivos persistidos
    location /uploads/ {
        proxy_pass http://backend:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
